auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash, session, abort
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, logout_user, login_required, current_user
from flask_bootstrap import Bootstrap
from models import User, Event
from forms import ChangePasswordForm, PasswordResetRequestForm, PasswordResetForm
from __init__ import db
import sys
import datetime
from projemail import send_email
from flask_login import current_user
from flask_mail import Mail, Message
import pyqrcode
from io import BytesIO


auth = Blueprint('auth', __name__)

@auth.before_app_request
def before_request():
    if current_user.is_authenticated and not current_user.confirmed and request.blueprint != 'auth' and request.endpoint != 'static':
        return redirect(url_for('auth.unconfirmed'))

@auth.route('/unconfirmed')
def unconfirmed():
    if current_user.is_anonymous or current_user.confirmed:
        return redirect(url_for('auth.login'))
    return render_template('unconfirmed.html')

@auth.route('/login')
def login():
    return render_template('login.html')

@auth.route('/login', methods=['POST'])
def login_post():
    email = request.form.get('email')
    password = request.form.get('password')
    token = request.form.get('token')
    remember = True if request.form.get('remember') else False

    user = User.query.filter_by(email=email).first()

    if not user or not check_password_hash(user.password, password) or not user.verify_totp(token):
        flash('Please check your login details and try again.')
        return redirect(url_for('auth.login'))

    login_user(user, remember=True)

    return redirect(url_for('main.profile'))

@auth.route('/twofactor')
def two_factor_setup():
    if 'username' not in session:
        return redirect(url_for('index'))
    user = User.query.filter_by(email=session['username']).first()
    if user is None:
        return redirect(url_for('index'))
    # since this page contains the sensitive qrcode, make sure the browser
    # does not cache it
    return render_template('two-factor-setup.html'), 200, {
        'Cache-Control': 'no-cache, no-store, must-revalidate',
        'Pragma': 'no-cache',
        'Expires': '0'}

@auth.route('/qrcode')
def qrcode():
    if 'username' not in session:
        abort(404)
    user = User.query.filter_by(email=session['username']).first()
    if user is None:
        abort(404)

    # for added security, remove username from session
    del session['username']

    # render qrcode for FreeTOTP
    url = pyqrcode.create(user.get_totp_uri())
    stream = BytesIO()
    url.svg(stream, scale=5)
    return stream.getvalue(), 200, {
        'Content-Type': 'image/svg+xml',
        'Cache-Control': 'no-cache, no-store, must-revalidate',
        'Pragma': 'no-cache',
        'Expires': '0'}


@auth.route('/signup')
def signup():
    return render_template('signup.html')

@auth.route('/signup', methods=['POST'])
def signup_post():
    email = request.form.get('email')
    name = request.form.get('name')
    password = request.form.get('password')

    user = User.query.filter_by(email=email).first()

    if user:
        flash('Email address already exists.')
        return redirect(url_for('auth.login'))

    new_user = User(email=email, name=name, password=generate_password_hash(password, method='sha256'))

    session['username'] = new_user.email

    db.session.add(new_user)
    db.session.commit()
    token = new_user.generate_confirmation_token()
    send_email(new_user.email, 'Confirm Your Account', 'confirm', user = user, token = token)
    flash('A confirmation email has been sent to you by email.')

    return redirect(url_for('auth.two_factor_setup'))


@auth.route('/confirm/<token>"')
@login_required
def confirm(token):
    if current_user.confirmed:
        return redirect(url_for('auth.login'))
    if current_user.confirm(token):
        db.session.commit()
        flash('You have confirmed your account. Thanks!')
    else:
        flash('The confirmation link is invalid or has expired.')
    return redirect(url_for('auth.login'))


@auth.route('/createEvent',methods=['GET','POST'])
def test():
    return render_template('eventCreation.html')

@auth.route('/change-password', methods=['GET', 'POST'])
@login_required
def change_password():
    form = ChangePasswordForm()
    if form.validate_on_submit():
        current_user.password = form.password.data
        current_user.password = generate_password_hash(current_user.password, method='sha256')
        db.session.add(current_user)
        db.session.commit()
        flash('Your password has been updated.')
        return redirect(url_for('main.index'))

    return render_template("change_password.html", form=form)

@auth.route('/reset', methods=['GET', 'POST'])
def password_reset_request():
    if not current_user.is_anonymous:
        return redirect(url_for('main.index'))
    form = PasswordResetRequestForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            token = user.generate_reset_token()
            send_email(user.email, 'Reset Your Password', 'reset_password_template', user=user, token=token)
        flash('An email with instructions to reset your password has been '
              'sent to you.')
        return redirect(url_for('auth.login'))
    return render_template('reset_password.html', form=form)


@auth.route('/reset/<token>', methods=['GET', 'POST'])
def password_reset(token):
    if not current_user.is_anonymous:
        return redirect(url_for('main.index'))
    form = PasswordResetForm()
    if form.validate_on_submit():
        if User.reset_password(token, form.password.data):
            db.session.commit()
            flash('Your password has been updated.')
            return redirect(url_for('auth.login'))
        else:
            return redirect(url_for('main.index'))
    return render_template('reset_password.html', form=form)

@auth.route('/eventCreated',methods=['POST'])
def createEvent():
    eventName = request.form.get("event")
    eventLocation= request.form.get("location")
    eventDate = request.form.get("date")
    eventType = request.form.get("types")
    eventTime = request.form.get("time")
    eventDescription= request.form.get("description")
    eventCreator = current_user.name

    eventDateTime = datetime.datetime.strptime(eventDate + " " + eventTime,  '%Y-%m-%d %H:%M')
    new_event = Event(name=eventName, type=eventType, description = eventDescription,  location=eventLocation,  creator=eventCreator, datetime=eventDateTime)

    db.session.add(new_event)
    db.session.commit()
    return redirect(url_for('main.profile'))


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))

templates/EventDisplay.html
{% extends "base.html" %}

{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />



  <div class="columns is-3">
  {% for event in events %}
  {% if event.id % 3 == 0 %}
  <div class="column">
  <div class="card">
  <div class="card-image">
    {% if party=="true" %}
      <img src="http://i.imgur.com/ynb2hR6.jpg" alt="party image">
      {% elif study=="true" %}
      <img src="//i.imgur.com/8uTjanA.jpg" alt="Placeholder image">
      {% else %}
      <img src="//i.imgur.com/MJzQbWbr.jpg" alt="Placeholder image">
      {% endif %}
  </div>
  <div class="card-content">
    <div class="media">
      <div class="media-left">
        <figure class="image is-48x48">
          <img src="https://bulma.io/images/placeholders/96x96.png" alt="Placeholder image">
        </figure>
      </div>
      <div class="media-content">
        <p class="title is-4" style="color: Black">{{ event.name }}</p>
        <p class="subtitle is-6" style="color: Black">@{{ event.creator}}</p>
      </div>
    </div>

    <div class="content">
      <div>
        <p>
            {{event.description}}
        </p>
      </div>

      <div>
        <b>Location: </b> <a style="color: blue">{{ event.location}}</a>.
        </div>
      <br>
      <time datetime="2016-1-1"> {{ event.datetime}}</time>
    </div>
    {% if event.datetime < curr_time %}
    <div> <p style="color:red;"> EXPIRED </p> </div>
    {% endif %}
  </div>
  </div>
  </div>
  </div>
  </nav>

  <div class ="columns is-3">
  {% else %}

  <div class="column is-one-thirds">
  <div class="card">
  <div class="card-image">
    {% if party=="true" %}
      <img src="http://i.imgur.com/ynb2hR6.jpg" alt="party image">
      {% elif study=="true" %}
      <img src="//i.imgur.com/8uTjanA.jpg" alt="Placeholder image">
      {% else %}
      <img src="//i.imgur.com/MJzQbWbr.jpg" alt="Placeholder image">
      {% endif %}
  </div>
  <div class="card-content">
    <div class="media">
      <div class="media-left">
        <figure class="image is-48x48">
          <img src="https://bulma.io/images/placeholders/96x96.png" alt="Placeholder image">
        </figure>
      </div>
      <div class="media-content">
        <p class="title is-4" style="color: Black">{{ event.name }}</p>
        <p class="subtitle is-6" style="color: Black">@{{ event.creator}}</p>
      </div>
    </div>

    <div class="content">
      <div>
        <p>
            {{event.description}}
        </p>
      </div>

      <div>
        <b>Location: </b> <a style="color: blue">{{ event.location}}</a>.
        </div>
      <br>
      <time datetime="2016-1-1"> {{ event.datetime}}</time>
    </div>
    {% if event.datetime < curr_time %}
    <div> <p style="color:red;"> EXPIRED </p> </div>
    {% endif %}
  </div>
  </div>
  </div>
  {% endif %}
  {% endfor %}

  </div>



{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
<head>
      <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />
</head>

<body>
    <h1>Conversation Starter </h1>
    <div> @ University of Rochester</div>

        <section class="hero is-primary is-fullheight">

            <div class="hero-head">
                <nav class="navbar">
                    <div class="container">

                        <div id="navbarMenuHeroA" class="navbar-menu">
                            <div class="navbar-end">
                                <a href="{{ url_for('main.index') }}" class="navbar-item">
                                    Home
                                </a>
                                {% if current_user.is_authenticated %}
                                <a href="{{ url_for('main.profile') }}" class="navbar-item">
                                    Profile
                                </a>
                                {% endif %}
                                {% if not current_user.is_authenticated %}
                                <a href="{{ url_for('auth.login') }}" class="navbar-item">
                                    Login
                                </a>
                                <a href="{{ url_for('auth.signup') }}" class="navbar-item">
                                    Sign Up
                                </a>
                                {% endif %}
                                {% if current_user.is_authenticated %}
                                <a href="{{ url_for('auth.logout') }}" class="navbar-item">
                                    Logout
                                </a>
                                {% endif %}
                                {% if current_user.is_authenticated %}
                                <a href="{{ url_for('auth.change_password') }}" class="navbar-item">
                                    Change Password
                                </a>
                                {% endif %}
                                  {% if not current_user.is_authenticated %}
                                <a href="{{ url_for('auth.password_reset_request') }}" class="navbar-item">
                                    Reset Password
                                </a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </nav>
            </div>

            <div class="hero-body">
                <div class="container has-text-centered">
                   {% block content %}
                   {% endblock %}
                </div>
            </div>
        </section>
    </body>
</html>

templates/change_password.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}



{% block content %}
  {% with messages = get_flashed_messages() %}
   {% if messages %}
      {% for message in messages %}
         {{ message }}
      {% endfor %}
    {% endif %}
    {% endwith %}

<h3 class="title">Change Your Password</h3>
<div class="box">
<div class="col-md-4">
    {{ wtf.quick_form(form) }}
</div>
</div>
{% endblock %}

templates/confirm.html
<p>Dear {{ current_user.name }},</p>
<p>Welcome to <b>ChatUR</b>!</p>
<p>To confirm your account please <a href="{{ url_for('auth.confirm', token=token, _external=True) }}">click here</a>.</p>
<p>Alternatively, you can paste the following link in your browser's address bar:</p>
<p>{{ url_for('auth.confirm', token=token, _external=True) }}</p>
<p>Sincerely,</p>
<p>The ChatUR Team</p>
<p><small>Note: replies to this email address are not monitored.</small></p>

templates/eventCreation.html
{% extends "base.html" %}

{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />


<div class="box">
<form action="/eventCreated" method="POST">
    <div class="field">
      <label for="event"> Event Name: </label>
        <input  type="text" name="event" placeholder="Event Name" autofocus="">
    </div>

    <div class="field">
      <label for="Location"> Location: </label>
        <input type="text" name="location" placeholder="Address" autofocus="">
    </div>

    <div class ="field">
      <label for="date"> Date: </label>
        <input type="Date" name="date" placeholder="Date" autofocus="">
    </div>

    <div class ="field">
      <label for="time"> Time: </label>
        <input type="time" name="time" autofocus="">
    </div>

    <div class="field">
      <label for="types"> Category: </label>
    <select name="types">
      <option value="Eat">Eat</option>
      <option value="Party">Party</option>
      <option value="Study">Study</option>
    </select>
    </div>

    <div class ="field">
      <label for="description"> Event description: </label>
      <textarea name="description" rows="4" cols="50"> </textarea>
    </div>


    </div>


    <button>Sign Up</button>
</form>

{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />

<h1 class="title">
  Welcome to Chatter!
</h1>
<h2 class="subtitle">
  CSC210 Group Project
</h2>
{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />
    {% with messages = get_flashed_messages() %}
   {% if messages %}
      {% for message in messages %}
         {{ message }}
      {% endfor %}
    {% endif %}
    {% endwith %}
    <h3 class="title">Login</h3>
    <div class="box">
        <form method="POST" action="/login">
            <div class="field">
                    <input type="email" name="email" placeholder="Your Email" >
            </div>

            <div class="field">
                    <input  type="password" name="password" placeholder="Your Password">
            </div>
            <div class="field">
                    <input  type="token" name="token" placeholder="Your Token">
            </div>
            <div class="field">
                <label class="checkbox">
                    <input type="checkbox">
                    Remember me
                </label>
            </div>
            <button>Login</button>
        </form>
    </div>



{% endblock %}

templates/profile.html
{% extends "base.html" %}

{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />

{% with messages = get_flashed_messages() %}
{% if messages %}
    <div class="notification is-info">
     <h1>{{ messages[0] }}</h1>
     </div>
{% endif %}
{% endwith %}

<h1 class="title" style="text-align:left; padding-buttom:25px;">  Welcome, {{ name }}! </h1>

<div class="columns">
  <div class="column">
    <div class ="tile notification is-info" style ="padding:40px">
      <div class= "centered">
        <form method="POST" action="/Eat">
        <button class="button is-info" style="font-weight: bold; font-size: 25px"" >Eat </button>
        </form>
    </div>
  </div>
  </div>
  <div class="column">
    <div class ="tile notification is-danger" style ="padding:40px">
        <div class= "centered">
          <form method="POST" action="/Party">
          <button class="button is-danger" style="font-weight: bold; font-size: 25px">Party</button>
          </form>
          </div>
          </div>
          </div>
  <div class="column">
    <div class ="tile notification is-warning" style ="padding:40px">
      <div class= "centered">
        <form method="POST" action="/Study">
        <button class="button is-warning" style="font-weight: bold; font-size: 25px" >Study </button>
        </form>
    </div>
  </div>
</div>
</div>
<form method="POST" action="/createEvent">
<button class="button">Create an event</button>
</form>

{% endblock %}

templates/reset_password.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}


<h3 class="title">Reset Password</h3>
<div class="box">
<div class="col-md-4">
    {{ wtf.quick_form(form) }}
</div>
</div>

{% endblock %}

templates/reset_password_template.html
<p>Dear User,</p>
<p>To reset your password <a href="{{ url_for('auth.password_reset', token=token, _external=True) }}">click here</a>.</p>
<p>Alternatively, you can paste the following link in your browser's address bar:</p>
<p>{{ url_for('auth.password_reset', token=token, _external=True) }}</p>
<p>If you have not requested a password reset simply ignore this message.</p>
<p>Sincerely,</p>
<p>The Flasky Team</p>
<p><small>Note: replies to this email address are not monitored.</small></p>

templates/signup.html
{% extends "base.html" %}

{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />
    <h3 class="title">Sign Up</h3>
    <div class="box">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="notification is-danger">
                {{ messages[0] }} Go to <a href="{{ url_for('auth.login') }}">login page</a>.
            </div>
        {% endif %}
        {% endwith %}
        <form action="/signup" method="POST">
            <div class="field">
                <input  type="email" name="email" placeholder="Email" autofocus="">
            </div>

            <div class="field">
                <input type="text" name="name" placeholder="Name" autofocus="">
            </div>

            <div class="field">
                <input  type="password" name="password" placeholder="Password">
            </div>

            <button>Sign Up</button>
        </form>
    </div>

{% endblock %}

templates/two-factor-setup.html
{% extends "base.html" %}

{% block content %}
    <h1>Two Factor Authentication Setup</h1>
    <p>You are almost done! Please start FreeOTP on your smartphone and scan the following QR Code with it:</p>
    <p><img id="qrcode" src="{{ url_for('auth.qrcode') }}"></p>
    <p>I'm done, take me to the <a href="{{ url_for('auth.login') }}">Login</a> page!</p>
{% endblock %}

templates/unconfirmed.html
{% extends "base.html" %}

{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />

<h1>
        Hello, {{ current_user.name }}!
</h1>

<h3>You have not confirmed your account yet.</h3>
    <p>
        Before you can access this site you need to confirm your account.
        Check your inbox, you should have received an email with a confirmation link.
    </p>
{% endblock %}